spring.application.name=auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/loan_management_system
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081

jwt.secret=MySuperSecretKeyForFlightApp123456789012345678901234567890123456789
jwt.expiration=86400000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=auth-service:${server.port}

logging.level.root=INFO
spring.cloud.config.enabled=false

